# [START cloudbuild_maven]
steps:
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ["test"]
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ["package", "-Dmaven.test.skip=true"]
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/protean-set-341414/wcs-spring", "--build-arg=JAR_FILE=target/wcs-1.0.0.jar", "."]
images: ["gcr.io/protean-set-341414/wcs-spring"]
# [END cloudbuild_maven]
